### ISSUE TITLE
Customise commands that pulse?

### ISSUE THREAD

**Issue by joostkremers** [minad/goggles#1]
Hi, thanks for this package. I've been using `volatile-highlights`, but I really wanted something that pulses. :smiley:

I was wondering if you have any plans to make the list of commands that pulse customisable? I don't really need a visual cue for `kill` and `delete`, or their `-region` variants.

**Comment by minad** [comment]
What do you mean precisely? You can define additional goggles using `goggles-define` if you need support for additional commands. These goggles can then be activated or deactivated individually.

Would you like to see different special behavior of the goggles per command? Such that kill always uses a specific color instead of the generic approach taken as of now (highlighting addition/deletion simply by counting the number of characters). I thought about adding something like this, but I did not yet make any steps in that direction.

My focus is on other projects right now. But PRs are certainly welcome, which add something like this, as long as it can be integrated cleanly with the existing infrastructure.

**Comment by minad** [comment]
@joostkremers After re-reading what you wrote - does it solve your issue if you deactivate the `kill` goggles?

~~~ elisp
(goggles-kill 'disable)
~~~

The list of googles enabled/defined by default is here: https://github.com/minad/goggles/blob/master/goggles.el#L175

**Comment by joostkremers** [comment]
Thanks for your quick reply. Yes, `(goggles-kill 'disable)` is apparently what I'm looking for. I did look at the code and read the doc string of `goggles-define`, but I thought that the `disable` argument was used internally for some bookkeeping (I didn't look at the code very closely. :smile:) I didn't realise it was a user-level configuration option.
